apiVersion: v1
kind: Secret
metadata:
  name: mysecrets
type: Opaque
data:
  postgres_password: QVZOU19Ia21hYXRYSkwxUWZINjBIbW5aIAo=
  aws_access_key_id: QUtJQVpJMkxFMlo2Q0xEU0dRWjc= 
  aws_secret_access_key: ajRsZlZXanBuTHZXTUxkSlE0WWlRWjM1RUdNbm9NeFFFL1hHVzZkSQo=
